# Generated by Django 4.1.2 on 2022-11-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passManagerApp', '0005_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='key',
            field=models.IntegerField(),
        ),
    ]
