# Generated by Django 4.1.2 on 2022-11-21 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passManagerApp', '0012_note_creat_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='creat_date',
            new_name='created_date',
        ),
    ]
