# Generated by Django 4.1.2 on 2022-11-21 07:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('passManagerApp', '0013_rename_creat_date_note_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='created_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
